language: ruby
rvm:
- 2.0.0
script:
- bundle exec rake publish
branches:
  only:
  - master
  - live
env:
  global:
  - secure: YSF234PH1jRf5L78nxtvJBzu1cbVT86ncabxsdg3ZJb62R3+9XVq2DZ8+hAt0YYutfj3L6ODTumYsCinP0BhTo9bA1b3SX56QyiIJ7DDzPctZZu2wzL5a8F0h3ZW3PW5UurJDfYogxgVHyeWWR/seM7OwwwzS25hJso2UabKs1I=
  - secure: QQokz8Zd1ycLOp2+kqJSTKjOmcIPKcxYElatWmgVgv9hQDlRZgx6iMqvSiOwP8Rypx4Bn08QrmDBvw1NEbfVfNLVzjMqJh34wS0HKs0ExVvA0NvvE6f8yeFPbXSN52o6momyF1F3sOoA/AaNQWg3xitcaSfwkcpg+6y3GVEuhsA=
