name: Feeding Texas
description: 
markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

baseurl: /feeding-texas
port: 4003
# url: 

twitter_handle: TexansVsHunger

# Permalink Configuration
permalink: /blog/:year/:month/:title

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'bower.json', '.bowerrc', 'config.rb', 'sass', 's3_website*.yml', 'Gruntfile.js', 'node_modules']

# Team directory used by the data_to_pages plugin.
location_dir: 'locations'
# contact_redirect: 'thanks'
tag_dir: 'blog/category'

# Blog pagination.  
# paginate: 10
# paginate_path: "blog/page:num"

# Setting relative permalink to false. See http://jekyllrb.com/docs/upgrading/.
relative_permalinks: false

# Collection definitions
collections:
  counties:
    output: true
    permalink: /zip/:path/
  staff:
    output: true
    permalink: /staff/:path/
  constituent-stories:
    output: false
  jobs:
    output: false
  calls-to-action:
    output: false

# Settings for sitemap_generator plugin.
# sitemap:
#     exclude:
#         - "/rss.xml"
#         - "/tag"
#     include_posts:
#         - "/index.html"
#         - "/blog/index.html"
#         - "/work/index.html"
#         - "/careers/index.html"

prose:
  # rooturl: "blog/_posts"
  siteurl: "http://thinkshout.github.io/feeding-texas/"
  media: "assets/images/blog"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "images"
        field: "hero"
          element: "text"
          label: "Hero image URL"
        field: "thumb"
          element: "text"
          label: "Thumbnail image URL"
      - name: "date"
        field:
          element: "text"
          label: "Date"
          placeholder: "2013-08-16"
      - name: "summary"
        field:
          element: "textarea"
          label: "Summary"
      - name: "author"
        field:
          element: "text"
          label: "Author"
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured"
          help: "The top 3 featured posts will appear on the home page."
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          help: "Enter one or more tags to categorize your post, E.g., Drupal, nonprofit, RedHen."
          alterable: true
    _calls-to-action:
      - name: "id"
        field:
          element:"number"
          label: "ID"
          help: "Unique ID number for call to action."
      - name: "link"
        field: "button_text"
          element: "text"
          label: "Button Text"
        field: "url"
          element: "text"
          label: "URL"
      -name: "image"
        field: "image"
          element: "text"
          label: "Image URL"
