name: Feeding Texas
description: 
markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

baseurl: /feeding-texas
port: 4003
# url: 

twitter_handle: TexansVsHunger

# Permalink Configuration
permalink: /blog/:year/:month/:title

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'bower.json', '.bowerrc', 'config.rb', 'sass', 's3_website*.yml', 'Gruntfile.js', 'node_modules']

# Team directory used by the data_to_pages plugin.
location_dir: 'locations'
# contact_redirect: 'thanks'
tag_dir: 'blog/category'

# Blog pagination.  
# paginate: 10
# paginate_path: "blog/page:num"

# Setting relative permalink to false. See http://jekyllrb.com/docs/upgrading/.
relative_permalinks: false

# Collection definitions
collections:
  counties:
    output: true
    permalink: /zip/:path/
  staff:
    output: true
    permalink: /staff/:path/
  constituent-stories:
    output: false
  jobs:
    output: false
  calls-to-action:
    output: false

# Settings for sitemap_generator plugin.
# sitemap:
#     exclude:
#         - "/rss.xml"
#         - "/tag"
#     include_posts:
#         - "/index.html"
#         - "/blog/index.html"
#         - "/work/index.html"
#         - "/careers/index.html"

prose:
  # rooturl: "blog/_posts"
  siteurl: "http://thinkshout.github.io/feeding-texas"
  media: "assets/images/blog"
  ignore:
    - .idea
    - /_includes
    - /_layouts
    - /_plugins
    - /_site
    - bower_components
    - .gitignore
    - _config.yml
    - bower.json
    - Gemfile
    - Gemfile.lock
    - Gruntfile.js
    - index.html
    - package.json
    - Rakefile
    - README.md
  metadata:
    _calls-to-action:
      - name: "id"
        field:
          element:"text"
          label: "ID"
          help: "Unique ID number for call to action."
      - name: "image"
        field:
          element: "text"
          label: "Image URL"
